site_name: Nyrule 3

theme: pulse

markdown_extensions:
  - markdown_captions
  - tables

extra_css:
  - assets/css/gallery.css
  - assets/css/justify.css
  - assets/css/headers.css
  - assets/css/toc-collapse.css
  - assets/css/navbar-collapse.css
  - assets/css/link.css
  - assets/css/table.css
  - assets/css/input.css

plugins:
  - search
  - macros
  - pageref:
      matches:
        - pattern: Nyrule
          page: docs/Lugares/Nyrule.md

        - pattern: Wish Crystal
          page: docs/Objetos/Wish_Crystal.md

        - pattern: Sepell
          page: docs/Lugares/Cidades/Sepell.md

        - pattern: Eldenhaven
          page: docs/Lugares/Cidades/Eldenhaven.md

        - pattern: Malgrim
          page: docs/Personagens/NPCs/Malgrim.md

        - pattern: Saevel( Caiphine)?
          page: docs/Personagens/NPCs/Saevel.md

        - pattern: Iaris
          page: docs/Personagens/PCs/Iaris.md

        - pattern: Luciel
          page: docs/Personagens/PCs/Luciel.md

        - pattern: Venessa
          page: docs/Personagens/PCs/Venessa.md

        - pattern: Lyra( Windsong)?
          page: docs/Personagens/PCs/Lyra.md

        - pattern: Kata da Pata de Gato
          page: docs/Worldbuild/Kata_Gato.md

        - pattern: Kumite da Raposa
          page: docs/Worldbuild/Kumite_Raposa.md

        - pattern: Wishrealm(, o Mundo dos Desejos)?
          page: docs/Lugares/Planos/Wishrealm.md
