site_name: Nyrule Wiki

theme:
  name: pulse
  navigation_depth: 3

repo_url: https://github.com/NiiMiyo/mkdocs-nyrule3/
edit_uri: blob/main/docs/

markdown_extensions:
  - markdown_captions
  - tables
  - abbr
  - md_in_html

extra_css:
  - assets/css/gallery.css
  - assets/css/justify.css
  - assets/css/headers.css
  - assets/css/toc-collapse.css
  - assets/css/navbar-collapse.css
  - assets/css/link.css
  - assets/css/table.css
  - assets/css/input.css
  - assets/css/blockquote.css
  - assets/css/ul.css
  - assets/css/next_prev.css

plugins:
  - search
  - macros
  - redirects:
      redirect_maps:
        Lugares/Plano_Material/Nyrule/Nyrule.md: index.md#o-mundo-de-nyrule
  - pageref
