site_name: Nyrule Wiki

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Ativar modo escuro
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Ativar modo claro

repo_url: https://github.com/NiiMiyo/mkdocs-nyrule3/
edit_uri: blob/main/docs/

markdown_extensions:
  - markdown_captions
  - tables
  - abbr
  - md_in_html
  - attr_list

extra_css:
  - assets/css/gallery.css
  - assets/css/justify.css
  - assets/css/headers.css
  - assets/css/toc-collapse.css
  - assets/css/navbar-collapse.css
  - assets/css/link.css
  - assets/css/table.css
  - assets/css/input.css
  - assets/css/blockquote.css
  - assets/css/ul.css
  - assets/css/next_prev.css

plugins:
  - search
  - macros
  - redirects:
      redirect_maps:
        Lugares/Plano_Material/Nyrule/Nyrule.md: index.md#o-mundo-de-nyrule
  - pageref
