site_name: Nyrule 3

theme:
  name: pulse
  locale: pt
  navigation_depth: 3
  prev_next_buttons_location: bottom
  collapse_navigation: true
  logo: /assets/images/logo.png

markdown_extensions:
  - markdown_captions
  - tables

extra_css:
  - assets/css/gallery.css
  - assets/css/justify.css
  - assets/css/headers.css
  - assets/css/toc-collapse.css
  - assets/css/navbar-collapse.css
  - assets/css/link.css
  - assets/css/table.css
  - assets/css/input.css
  - assets/css/blockquote.css
  - assets/css/ul.css

plugins:
  - search
  - macros
  - pageref:
      matches:
        - pattern: Nyrule
          page: docs/index.md

        - pattern: Wish Crystal
          page: docs/Objetos/Wish_Crystal.md

        - pattern: Sepell
          page: docs/Lugares/Cidades/Sepell.md

        - pattern: Eldenhaven
          page: docs/Lugares/Cidades/Eldenhaven.md

        - pattern: Malgrim(, o Mago das Almas)?
          page: docs/Personagens/NPCs/Vilões/Malgrim.md

        - pattern: Saevel( Caiphine)?
          page: docs/Personagens/NPCs/Vilões/Saevel.md

        - pattern: Iaris
          page: docs/Personagens/PCs/Iaris.md

        - pattern: Luciel
          page: docs/Personagens/PCs/Luciel.md

        - pattern: Venessa
          page: docs/Personagens/PCs/Venessa.md

        - pattern: Lyra( Windsong)?
          page: docs/Personagens/PCs/Lyra.md

        - pattern: Kata da Pata de Gato
          page: docs/Worldbuild/Kata_Gato.md

        - pattern: Kumite da Raposa
          page: docs/Worldbuild/Kumite_Raposa.md

        - pattern: Wishrealm(, o Mundo dos Desejos)?
          page: docs/Lugares/Planos/Wishrealm.md

        - pattern: Kenshima
          page: docs/Lugares/Cidades/Kenshima.md

        - pattern: Apoçãotrar o Crowhey
          page: docs/Objetos/Apocaotrar_Crowhey.md

        - pattern: Crowhey( Semore)?
          page: docs/Personagens/NPCs/Crowhey.md

        - pattern: Rue
          page: docs/Personagens/NPCs/Rue.md

        - pattern: Ostfer
          page: docs/Personagens/NPCs/Ostfer.md

        - pattern: O Observador
          page: docs/Personagens/NPCs/O_Observador.md

        - pattern: Plano Material
          page: docs/Lugares/Planos/Plano_Material.md

        - pattern: Plano Etéreo
          page: docs/Lugares/Planos/Plano_Etéreo.md

        - pattern: Alma(s)?
          page: docs/Worldbuild/Corpo_alma_mente.md#a-alma

        - pattern: Corpo(s)?
          page: docs/Worldbuild/Corpo_alma_mente.md#o-corpo

        - pattern: Mente(s)?
          page: docs/Worldbuild/Corpo_alma_mente.md#a-mente
